
package bigws.todows;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.8
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "ToDoWebServiceService", targetNamespace = "http://todows.bigws/", wsdlLocation = "http://localhost:8081/todoServer?wsdl")
public class ToDoWebServiceService
    extends Service
{

    private final static URL TODOWEBSERVICESERVICE_WSDL_LOCATION;
    private final static WebServiceException TODOWEBSERVICESERVICE_EXCEPTION;
    private final static QName TODOWEBSERVICESERVICE_QNAME = new QName("http://todows.bigws/", "ToDoWebServiceService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8081/todoServer?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        TODOWEBSERVICESERVICE_WSDL_LOCATION = url;
        TODOWEBSERVICESERVICE_EXCEPTION = e;
    }

    public ToDoWebServiceService() {
        super(__getWsdlLocation(), TODOWEBSERVICESERVICE_QNAME);
    }

    public ToDoWebServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    /**
     * 
     * @return
     *     returns ToDoWebService
     */
    @WebEndpoint(name = "ToDoWebServicePort")
    public ToDoWebService getToDoWebServicePort() {
        return super.getPort(new QName("http://todows.bigws/", "ToDoWebServicePort"), ToDoWebService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ToDoWebService
     */
    @WebEndpoint(name = "ToDoWebServicePort")
    public ToDoWebService getToDoWebServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://todows.bigws/", "ToDoWebServicePort"), ToDoWebService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (TODOWEBSERVICESERVICE_EXCEPTION!= null) {
            throw TODOWEBSERVICESERVICE_EXCEPTION;
        }
        return TODOWEBSERVICESERVICE_WSDL_LOCATION;
    }

}
